[general]
background = "#14131a"
foreground = "#00d5ff"
insertbackground = "#ffffff"
insertwidth = 1
inactiveselectbackground = "#555555"
highlightthickness = 0
borderwidth = 0

[selection]
background = "#555555"
foreground = "#ffffff"

[syntax]
"Token.Text" = "#ffffff"
"Token.Other" = "#ffffff"
"Token.Eror" = "#e34646"
"Token.Whitespace" = "#ffffff"
"Token.Escape" = "#c908ff"
"Token.Keyword" = "#d170e9"
"Token.Keyword.Constant" = "#00fff7"
"Token.Punctuation" = "#80cbc4"
"Token.Name.Attribute" = "#58abff"
"Token.Name.Builtin" = "#58abff"
"Token.Name.Class" = "#7dff7d"
"Token.Name.Constant" = "#00fff7"
"Token.Name.Decorator" = "#007fff"
"Token.Name.Entity" = "#ffbd00"
"Token.Name.Exception" = "#e34646"
"Token.Name.Function" = "#ffbd00"
"Token.Name.Function.Magic" = "#58abff"
"Token.Name.Label" = "#58abff"
"Token.Name.Namespace" = "#58abff"
"Token.Name.Other" = "#58abff"
"Token.Name.Tag" = "#80cbc4"
"Token.Name.Variable" = "#58abff"
"Token.Name.Variable.Class" = "#58abff"
"Token.Name.Variable.Global" = "#58abff"
"Token.Name.Variable.Instance" = "#58abff"
"Token.Name.Variable.Magic" = "#58abff"
"Token.Operator" = "#ff8058"
"Token.Operator.Word" = "#d170e9"
"Token.Comment" = "#949494"
"Token.Comment.Hashbang" = "#949494"
"Token.Comment.Multiline" = "#949494"
"Token.Comment.Preproc" = "#949494"
"Token.Comment.Preprocfile" = "#949494"
"Token.Comment.Single" = "#949494"
"Token.Comment.Special" = "#949494"
"Token.Literal.Number.Bin" = "#7dff7d"
"Token.Literal.Number.Float" = "#7dff7d"
"Token.Literal.Number.Hex" = "#7dff7d"
"Token.Literal.Number.Integer" = "#7dff7d"
"Token.Literal.Number.Integer.Long" = "#7dff7d"
"Token.Literal.Number.Oct" = "#7dff7d"
"Token.Literal.String.Affix" = "#d47337"
"Token.Literal.String.Char" = "#d47337"
"Token.Literal.String.Delimeter" = "#d47337"
"Token.Literal.String.Doc" = "#d47337"
"Token.Literal.String.Double" = "#d47337"
"Token.Literal.String.Escape" = "#c908ff"
"Token.Literal.String.Heredoc" = "#d47337"
"Token.Literal.String.Interpol" = "#d47337"
"Token.Literal.String.Other" = "#d47337"
"Token.Literal.String.Regex" = "#d47337"
"Token.Literal.String.Single" = "#d47337"
"Token.Literal.String.Symbol" = "#d47337"

  [syntax."Token.Keyword.Declaration"]
  foreground = "#d170e9"

    [syntax."Token.Keyword.Declaration".font]
    bold = true

  [syntax."Token.Keyword.Namespace"]
  foreground = "#d170e9"

    [syntax."Token.Keyword.Namespace".font]
    bold = true

  [syntax."Token.Keyword.Pseudo"]
  foreground = "#d170e9"

    [syntax."Token.Keyword.Pseudo".font]
    bold = true

  [syntax."Token.Keyword.Reserved"]
  foreground = "#d170e9"

    [syntax."Token.Keyword.Reserved".font]
    bold = true

  [syntax."Token.Keyword.Type"]
  foreground = "#d170e9"

    [syntax."Token.Keyword.Type".font]
    bold = true

  [syntax."Token.Keyword.Other"]
  foreground = "#d170e9"

    [syntax."Token.Keyword.Other".font]
    bold = true

  [syntax."Token.Name.Builtin.Pseudo"]
  foreground = "#fd9621"

    [syntax."Token.Name.Builtin.Pseudo".font]
    bold = true
